export const currentLanguageData = {
  title: "ఆంధ్రప్రదేశ్ భవన మరియు ఇతర నిర్మాణ కార్మికుల నమోదు – ఫారం-XXVII",
  personalDetails: " కార్మికుడి వివరాలు",
  titler: " నమోదు ప్రివ్యూ",
  field: {
    personalDetails: " కార్మికుడి వివరాలు",
    soWo: "తండ్రి / భర్త పేరు",
    workerId: "కార్మికుడి ఐడి",
    aadhaarNo: "ఆధార్ నంబర్",
    mother: "తల్లి",
    father: "తండ్రి",
    brother: "అన్న / తమ్ముడు",
    sister: "అక్క / చెల్లి",
    grandFather: "తాత",
    grandMother: "అమ్మమ్మ / నానమ్మ",
    spouse: "భార్య / భర్త",
    daughter: "కూతురు",
    son: "కొడుకు",
    aadhaarNo: "ఆధార్ నంబర్",
    firstName: "పేరు",
    lastName: "ఇంటి పేరు",
    gender: "లింగం",
    male: "పురుషుడు",
    female: "స్త్రీ",
    other: "ఇతరులు",
    maritalStatus: "వివాహ స్థితి",
    otherContactNumber: " ప్రత్యామ్నాయ సంప్రదింపు సంఖ్య",
    religion: "మతం",
    caste: "కులం",
    subCaste: "ఉపకులం",
    phoneNo: "ఫోన్ నంబర్",
    dob: "పుట్టిన తేది",
    fatherName: "తండ్రి / భర్త పేరు",
    familyDetaile: "కుటుంబ సభ్యుల వివరాలు",
    familyMember: "కుటుంబ సభ్యుడు",
    relation: "సంబంధం",
    memberName: "కుటుంబ సభ్యుని పేరు",
    memberDob: "కుటుంబ సభ్యుని వయసు",
    isNomine: "నామినీనా?",
    nominePer: "లాభ్య శాతం (%)",
    bankDetailes: "బ్యాంక్ వివరాలు",
    ifscCode: "IFSC కోడ్",
    bankName: "బ్యాంక్ పేరు",
    branchName: "శాఖ పేరు",
    bankAccountNo: "బ్యాంక్ ఖాతా నంబర్",
    rbankAccountNo: "బ్యాంక్ ఖాతా నంబర్ మళ్లీ నమోదు చేయండి",
    nameInBank: "బ్యాంక్ ఖాతాలో ఉన్న పేరు",
    address: "చిరునామా వివరాలు",
    paddress: "శాశ్వత చిరునామా",
    state: "రాష్ట్రం",
    permanentDistrictCode: "జిల్లా",
    permanentMadalCode: "మండలం",
    permanentVillageCode: "గ్రామం",
    presentMadalCode: "మండలం",
    presentVillageCode: "గ్రామం",
    presentPincode: "పిన్ కోడ్",
    presentDoorNo: "డోర్ నంబర్",
    presentAddress: "చిరునామా",
    presentDivision: "డివిజన్ / వార్డు నంబర్",
    presentLandMark: "ల్యాండ్ మార్క్ / ప్రాంతం",
    presentCity: "పట్టణం / నగరం",
    otherDetailes: "ఇతర వివరాలు",
    isNregs: "మీరు VB-GRAM G కార్మికుడా?",
    jobCardNo: "జాబ్ కార్డ్ నంబర్",
    isPermanent: "మీ ప్రస్తుత చిరునామా శాశ్వత చిరునామా లాగే ఉందా?",
    PresentAddress: "ప్రస్తుత చిరునామా",
    isUnionMember: "మీరు ట్రేడ్ యూనియన్ సభ్యుడా?",
    unionName: "📍యూనియన్ పేరు",
    regNo: "నమోదు సంఖ్య",
    workPlace: "ప్రస్తుత పని ప్రదేశ వివరాలు",
    workDetails: "పని వివరాలు",
    empName: "యజమాని పేరు",
    presentOfficeName: "నిర్మాణ సంస్థ పేరు",
    typeOfWork: "వృత్తి రకం",
    title: "ప్రస్తుత పని ప్రదేశ వివరాలు",
    employerName: "యజమాని పేరు",
    constructionName: "నిర్మాణ సంస్థ పేరు",
    tradeWork: "వృత్తి రకం",
    training: "మీకు శిక్షణ అవసరమా?",
    district: "జిల్లా",
    mandal: "మండలం",
    village: "గ్రామం",
    pincode: "పిన్ కోడ్",
    doorNo: "డోర్ నంబర్",
    address: "చిరునామా",
    otherTradeWork: "మీ పని స్వభావాన్ని పేర్కొనండి",
    workCapability: "మీకు శిక్షణ అవసరమా?",
    migrant: "వలస కార్మికుడు",
    isMigrant: "మీరు వలస కార్మికుడా?",
    upload: "అప్లోడ్స్",
    photoDesc: "పాస్‌పోర్ట్ సైజ్ ఫోటో",
    signatureDesc: "సంతకం",
    documents: "పత్రాలు",
    payment: "చెల్లింపు",
    selfAffidavitDesc: "స్వీయ ప్రకటన",
    payment: "చెల్లింపు",
    fee: "నమోదు ఫీజు ₹50 ఒకసారి మరియు సంవత్సరానికి ₹12 చందా",
    years: "సంవత్సరాలు",
    amount: "మొత్తం",
    selfDeclaration: "స్వీయ ప్రకటన",
    selfCheck:
      "నేను ఇక్కడ ఇచ్చిన సమాచారం నా తెలిసినంతవరకు నిజమని ప్రకటిస్తున్నాను. తరువాత ఈ సమాచారంలో ఏదైనా తప్పుడు సమాచారం ఉన్నట్లు తేలితే, నా నమోదు రద్దు చేయబడవచ్చు మరియు నాకు లేదా నా కుటుంబ సభ్యులకు ఇచ్చిన ప్రయోజనాలు తిరిగి వసూలు చేయబడతాయి.",
  },
};
